### ISSUE TITLE
Allow color codes without a #-prefix

### ISSUE THREAD

**Issue by mcz-sz** [janstuemmel/aws-role-switch#226]
`aws-extend-switch`-roles reads and displays hex color codes without a `#`-prefix in the config.
Example:
```
color = 00ff7f
```
However, this extension would only read the color if it is prefixed using a `#`

For compatibility and ease-of-use it would make sense to allow this type of color coding.
This would allow users to copy their config from the other extension to this one without updating their configuration.

**Comment by janstuemmel** [comment]
could parse both, with and without `#` to avoid breaking change

**Comment by janstuemmel** [comment]
noch nicht gemergt ^
