### ISSUE TITLE
Support configuring region and role_arn

### ISSUE THREAD

**Issue by michellemay** [janstuemmel/aws-role-switch#30]
It would be really helpful to allow adding a region to each profile

**Comment by janstuemmel** [comment]
Hey, `role_arn` is supported at master. Should come with next release...

I already thought about adding `region` to the config. What would be the benefit's in your perspective...

**Comment by michellemay** [comment]
Hi! 

For some tasks, I need to change role and region at the same time.  Our software is multi region and I do not have access to all task types in all regions. (least privileges policy)

tilfinltd/aws-extend-switch-roles supports changing region and role at the same time.. But I like your extension better because of the groups.

**Comment by janstuemmel** [comment]
> Hi!
> 
> For some tasks, I need to change role and region at the same time. Our software is multi region and I do not have access to all task types in all regions. (least privileges policy)
> 
> tilfinltd/aws-extend-switch-roles supports changing region and role at the same time.. But I like your extension better because of the groups.

Hey. I mixed your two tickets, sry. I closed #31 now. 

But i do not exactly understand what you mean by changing region and and role at the same time. 
Do you mean, when you click a role, you assume the role and change the region from the actual region to the predefined (in config) one?

**Comment by michellemay** [comment]
Yes exactly.

I would like to be able to configure both role and region so I can change
both when switching. In our setup, role and regions may come together in
some cases but not in other.

**Comment by janstuemmel** [comment]
PR #32 add's region support in config. I will do a bit of manual testing and release a new version in the next week...

**Comment by michellemay** [comment]
Is it possible that this feature is not working anymore ?
