### ISSUE TITLE
role_arn does not seems to be working.

### ISSUE THREAD

**Issue by michellemay** [janstuemmel/aws-role-switch#35]
When I specify role_arn in the config instead of aws_account_id/role_name, switching to this role bring me to the switch role page in aws.  

It probably have something to do with role parsing.  

`role_arn = arn:aws:iam::12345678:role/user-role-abc-xyz`

I end up with aws switch role with only `user` as role name.

Closer inspection of the code seems to confirm this.  At tthe line https://github.com/janstuemmel/aws-role-switch/blob/b7795c9d756d5ad31db2b97416d087b93f762398/src/common/config/mapper.ts#L61 the regex only limit role name to `\w+`.  

[AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html) states: 

> Names of users, groups, roles, policies, instance profiles, and server certificates must be alphanumeric, including the following common characters: plus (+), equal (=), comma (,), period (.), at (@), underscore (_), and hyphen (-).

**Comment by janstuemmel** [comment]
Thats absolutly correct. Didn't see that, cause' our roles are all camelcase: `SomeRoleToAssume`. I fixed that with #36. Feel free to review the changes.

**Comment by janstuemmel** [comment]
version `0.5.0` is live now
